// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzqrAzHWUZJIHMH3RuK52ABEeLgPH10R0',
    appId: '1:491559516994:web:d7f8d94a2a275ed27be6db',
    messagingSenderId: '491559516994',
    projectId: 'puskesmas-cisandea',
    authDomain: 'puskesmas-cisandea.firebaseapp.com',
    storageBucket: 'puskesmas-cisandea.appspot.com',
    measurementId: 'G-3R416W6FDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAntSsBNvJNWKJnGPrtwusXeMOt--i4aZw',
    appId: '1:491559516994:android:22b3c4dee7b385927be6db',
    messagingSenderId: '491559516994',
    projectId: 'puskesmas-cisandea',
    storageBucket: 'puskesmas-cisandea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2h8XJ87pFmeMGjDUnPnA_960psSfU3GE',
    appId: '1:491559516994:ios:ee10883524ba3f627be6db',
    messagingSenderId: '491559516994',
    projectId: 'puskesmas-cisandea',
    storageBucket: 'puskesmas-cisandea.appspot.com',
    iosBundleId: 'com.example.puskesmasCisadea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2h8XJ87pFmeMGjDUnPnA_960psSfU3GE',
    appId: '1:491559516994:ios:ee10883524ba3f627be6db',
    messagingSenderId: '491559516994',
    projectId: 'puskesmas-cisandea',
    storageBucket: 'puskesmas-cisandea.appspot.com',
    iosBundleId: 'com.example.puskesmasCisadea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzqrAzHWUZJIHMH3RuK52ABEeLgPH10R0',
    appId: '1:491559516994:web:f899eb703382996e7be6db',
    messagingSenderId: '491559516994',
    projectId: 'puskesmas-cisandea',
    authDomain: 'puskesmas-cisandea.firebaseapp.com',
    storageBucket: 'puskesmas-cisandea.appspot.com',
    measurementId: 'G-L20K0JCN4C',
  );
}
